# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -path ./docs -prune -o -type f -name ".DS_Store" -print -exec rm -f {} +
      - find . -path ./docs -prune -o -type f -name "core" -print -exec rm -f {} +
    silent: false

  init:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # remove system files
      - task remove_system_files
      # キャッシュクリア (skillsの読み込み時にcacheが悪さすることが多い)
      - rm -rf ./.devcontainer/.state/claude/plugins/cache/*
    silent: false

  fmt:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - treefmt -vv
    silent: false
